### ISSUE TITLE
[Enhancement] 为自定义命名增加格式检查

### ISSUE THREAD

**Issue by Yurzi** [Kuingsmile/PicHoro#19]
## 环境

操作系统: MIUI13
应用版本: 1.8.3

## 问题描述

在配置好图床后，并使用自定义命名时，若自定义命名格式错误则在上传页使用任何一个悬浮按钮均无法启动上传。同时没有任何提示。

## 日志

无

## 建议

增加一个自定义命名格式的检查或者异常处理
增加一个日志导出功能

**Comment by Kuingsmile** [comment]
> ## 环境
> 操作系统: MIUI13 应用版本: 1.8.3
> 
> ## 问题描述
> 在配置好图床后，并使用自定义命名时，若自定义命名格式错误则在上传页使用任何一个悬浮按钮均无法启动上传。同时没有任何提示。
> 
> ## 日志
> 无
> 
> ## 建议
> 增加一个自定义命名格式的检查或者异常处理 增加一个日志导出功能

已复现成功，会在下一个版本V1.84中增加格式检查和错误日志导出功能~

**Comment by Yurzi** [comment]
还有一个问题
似乎并不支持使用`/`

以下规则无法使用:
`{Y}/{m}/{md5}-{str-4}`

**Comment by Kuingsmile** [comment]
> 还有一个问题
> 似乎并不支持使用`/`
> 
> 以下规则无法使用:
> `{Y}/{m}/{md5}-{str-4}`

应该是'/'和目录分隔符号冲突了，这么设置的话拼接完整的路径的时候会识别错误，比如'test/2022/10/31/example.txt'里年月日都会被识别成目录，所以不建议在文件名中使用'/'

**Comment by Yurzi** [comment]
> > 还有一个问题
> > 似乎并不支持使用`/`
> > 以下规则无法使用:
> > `{Y}/{m}/{md5}-{str-4}`
> 
> 应该是'/'和目录分隔符号冲突了，这么设置的话拼接完整的路径的时候会识别错误，比如'test/2022/10/31/example.txt'里年月日都会被识别成目录，所以不建议在文件名中使用'/'，同样的，'\'也不建议使用，有可能会被识别成转义字符，比如'\n' '\t'啥的

但是在使用对象存储的时候常常会希望将文件存放在一定的文件夹下，咱感觉 `/` 的问题和会把文件重命名的问题是关联的

**Comment by Kuingsmile** [comment]
改好了 现在{Y}/{m}/{md5}这种格式的重命名，会自动在对象存储时创建两级目录

**Comment by Kuingsmile** [comment]
> ## 环境
> 操作系统: MIUI13 应用版本: 1.8.3
> 
> ## 问题描述
> 在配置好图床后，并使用自定义命名时，若自定义命名格式错误则在上传页使用任何一个悬浮按钮均无法启动上传。同时没有任何提示。
> 
> ## 日志
> 无
> 
> ## 建议
> 增加一个自定义命名格式的检查或者异常处理 增加一个日志导出功能

1. 已增加命名格式的检查，同时增加了异常错误的日志记录和查看功能，支持导出为txt文件并同步复制到剪贴板
2. 现在自定义重命名可以使用’/‘来创建文件夹了（仅对腾讯云等对象存储服务有效）
以上变更将在V1.8.4版本中生效。

**Comment by Yurzi** [comment]
辛苦了作者
<img src="https://s2.loli.net/2022/10/31/1jPhJoYsQ3EqfHb.jpg" width = "64" height = "64" alt="比心"/>
