### ISSUE TITLE
[Bug] 上传图片重命名会重命名本地文件

### ISSUE THREAD

**Issue by Yurzi** [Kuingsmile/PicHoro#20]
## 环境

操作系统: MIUI13
应用版本: 1.8.3

## 问题描述

在使用重命名功能时（包括 时间戳 随机字符串）会讲本地的文件也进行重命名。

## 日志

无

## 建议

请对上传的文件对象建立一个新的类，用于本地和远程文件的绑定。不要直接调用 `File` 对象的 `rename` 方法。

**Comment by Yurzi** [comment]
翻了一下源码，没怎么看明白，不太敢动手，只能寄希望于作者。
![啊啊啊](https://s2.loli.net/2022/10/31/zYvIPuBp5q8F7K3.jpg)

**Comment by Kuingsmile** [comment]
> ## 环境
> 操作系统: MIUI13 应用版本: 1.8.3
> 
> ## 问题描述
> 在使用重命名功能时（包括 时间戳 随机字符串）会讲本地的文件也进行重命名。
> 
> ## 日志
> 无
> 
> ## 建议
> 请对上传的文件对象建立一个新的类，用于本地和远程文件的绑定。不要直接调用 `File` 对象的 `rename` 方法。



> ## 环境
> 操作系统: MIUI13 应用版本: 1.8.3
> 
> ## 问题描述
> 在使用重命名功能时（包括 时间戳 随机字符串）会讲本地的文件也进行重命名。
> 
> ## 日志
> 无
> 
> ## 建议
> 请对上传的文件对象建立一个新的类，用于本地和远程文件的绑定。不要直接调用 `File` 对象的 `rename` 方法。

可以

**Comment by Kuingsmile** [comment]
> ## 环境
> 操作系统: MIUI13 应用版本: 1.8.3
> 
> ## 问题描述
> 在使用重命名功能时（包括 时间戳 随机字符串）会讲本地的文件也进行重命名。
> 
> ## 日志
> 无
> 
> ## 建议
> 请对上传的文件对象建立一个新的类，用于本地和远程文件的绑定。不要直接调用 `File` 对象的 `rename` 方法。

已完成功能修改，现在上传时不会重命名本地文件了，重命名只对远程文件名起作用。
该变化将在V1.8.4版本中更新。
