### ISSUE TITLE
增加对于s3存储的支持

### ISSUE THREAD

**Issue by andatoshiki** [Kuingsmile/PicHoro#25]
### PicHoro的版本

V1.8.3

### 系统信息

Redmi Note 11 pro

### 功能请求

增加对于S3存储的支持，现在大面积的存储桶比如backblaze，R2，AWS都支持S3 compatible API可否增加对于S3上传的支持？

**Comment by Kuingsmile** [comment]
> ### PicHoro的版本
> V1.8.3
> 
> ### 系统信息
> Redmi Note 11 pro
> 
> ### 功能请求
> 增加对于S3存储的支持，现在大面积的存储桶比如backblaze，R2，AWS都支持S3 compatible API可否增加对于S3上传的支持？

@andatoshiki 可以的，但预期不会在下个版本就添加，我需要先测试和研究下API接口，按照目前的开发路线图，估计会在1.9.0版本时加入。1.88和1.89版本我规划先添加对Github和Imgur管理功能的支持。

**Comment by andatoshiki** [comment]
> > ### PicHoro的版本
> > V1.8.3
> > ### 系统信息
> > Redmi Note 11 pro
> > ### 功能请求
> > 增加对于S3存储的支持，现在大面积的存储桶比如backblaze，R2，AWS都支持S3 compatible API可否增加对于S3上传的支持？
> 
> @andatoshiki 可以的，但预期不会在下个版本就添加

其实很想一起参与贡献PR，可惜知识盲区卡在dart了，picgo的桌面版本有自己用typescript写的插件

**Comment by Kuingsmile** [comment]
> > > ### PicHoro的版本
> > > V1.8.3
> > > ### 系统信息
> > > Redmi Note 11 pro
> > > ### 功能请求
> > > 增加对于S3存储的支持，现在大面积的存储桶比如backblaze，R2，AWS都支持S3 compatible API可否增加对于S3上传的支持？
> > 
> > 
> > @andatoshiki 可以的，但预期不会在下个版本就添加
> 
> 其实很想一起参与贡献PR，可惜知识盲区卡在dart了，picgo的桌面版本有自己用typescript写的插件

@andatoshiki 
进度更新：目前已经完成了初步的S3 compatible API的支持和测试，您提到的三个服务商backblaze，R2，AWS都已进行了测试可用，1.91版本发布时将完成添加

**Comment by andatoshiki** [comment]
> > > > ### PicHoro的版本
> > > > V1.8.3
> > > > ### 系统信息
> > > > Redmi Note 11 pro
> > > > ### 功能请求
> > > > 增加对于S3存储的支持，现在大面积的存储桶比如backblaze，R2，AWS都支持S3 compatible API可否增加对于S3上传的支持？
> > > 
> > > 
> > > @andatoshiki 可以的，但预期不会在下个版本就添加
> > 
> > 其实很想一起参与贡献PR，可惜知识盲区卡在dart了，picgo的桌面版本有自己用typescript写的插件
> 
> @andatoshiki 
> 进度更新：目前已经完成了初步的S3 compatible API的支持和测试，您提到的三个服务商backblaze，R2，AWS都已进行了测试可用，1.91版本发布时将完成添加

Thank you for your workaround!

**Comment by Kuingsmile** [comment]
> > > > > ### PicHoro的版本
> > > > > V1.8.3
> > > > > ### 系统信息
> > > > > Redmi Note 11 pro
> > > > > ### 功能请求
> > > > > 增加对于S3存储的支持，现在大面积的存储桶比如backblaze，R2，AWS都支持S3 compatible API可否增加对于S3上传的支持？
> > > > 
> > > > 
> > > > @andatoshiki 可以的，但预期不会在下个版本就添加
> > > 
> > > 
> > > 其实很想一起参与贡献PR，可惜知识盲区卡在dart了，picgo的桌面版本有自己用typescript写的插件
> > 
> > 
> > @andatoshiki
> > 进度更新：目前已经完成了初步的S3 compatible API的支持和测试，您提到的三个服务商backblaze，R2，AWS都已进行了测试可用，1.91版本发布时将完成添加
> 
> Thank you for your workaround!

#34 
V1.9.1版本更新，以增加对S3 compatible API的支持，此外，由于兼容S3   @@api的平台较多，单个配置显然不太适合，因此，本版本还增加了单种图床最多可以设置26个备用配置的功能，备用配置可切换为默认配置，方便快速在不同的平台或同一图床的不同存储桶或目录之间进行切换
@andatoshiki

**Comment by Kuingsmile** [comment]
关闭issue
