### ISSUE TITLE
webdav_manage_api not found

### ISSUE THREAD

**Issue by SeongBrave** [Kuingsmile/PicHoro#42]
### PicHoro的版本

commit: 7f01429

### 系统信息

main

### 问题重现 | Bug reproduce

<img width="700" alt="image" src="https://user-images.githubusercontent.com/10784393/207257084-6648583b-de47-47c4-a690-bc908cd64337.png">

**Comment by Kuingsmile** [comment]
更新的时候忘了上传了…我晚上同步下@SeongBrave

**Comment by Kuingsmile** [comment]
> ### PicHoro的版本
> commit: [7f01429](https://github.com/Kuingsmile/PicHoro/commit/7f01429cd7c01aeabb81943d6af0c45268c479c7)
> 
> ### 系统信息
> main
> 
> ### 问题重现 | Bug reproduce
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/10784393/207257084-6648583b-de47-47c4-a690-bc908cd64337.png">
> 
> ### 相关日志 | Logs
> _No response_

已上传缺失文件
