### ISSUE TITLE
[Bug]: 安卓13外观模式

### ISSUE THREAD

**Issue by Jamie-Wan** [Kuingsmile/PicHoro#46]
### PicHoro的版本

v1.9.8

### 系统信息

OPPO Find X3

### 问题重现 | Bug reproduce

ColorOS13.0，主题设置选择跟随系统后出现灰屏，退出重新打开无效。需要卸载重新安装

**Comment by Kuingsmile** [comment]
> ### PicHoro的版本
> v1.9.8
> 
> ### 系统信息
> OPPO Find X3
> 
> ### 问题重现 | Bug reproduce
> ColorOS13.0，主题设置选择跟随系统后出现灰屏，退出重新打开无效。需要卸载重新安装
> 
> ### 相关日志 | Logs
> _No response_

已复现，定位bug位置是’/lib/utils/theme_provider.dart‘文件中的setTheme函数。

bug产生原因：
setTheme函数中，当设置主题为跟随系统时，输入参数为'auto‘，下面的代码错误的将'auto’未经转换直接赋值给了_keyThemeColor，导致’/lib/main.dart‘中的`themeDataMap[appInfo.keyThemeColor]!`部分代码无法通过非空值检验，从而导致APP无法启动。
```dart
SpUtil.putString('key_theme_color', themeColor);
_keyThemeColor = themeColor;
```
如下修改后bug得到修复
```dart
SpUtil.putString('key_theme_color', _themeColor);
_keyThemeColor = _themeColor;
```

该bug将在V1.99版本中进行修复，感谢反馈，在V1.98版本中请暂时不要选择跟随系统避免无法启动APP。

**Comment by Kuingsmile** [comment]
新版本已修复
