### ISSUE TITLE
[Feature]: 希望加入ftp设置自定义域名的功能

### ISSUE THREAD

**Issue by meetcode** [Kuingsmile/PicHoro#48]
### PicHoro的版本

v1.8.3

### 系统信息

vivo

### 功能请求

希望加入ftp设置自定义域名的功能，因为我是上传到自己的网站，图片链接通过网站域名的形式访问，希望图片默认复制路径是网站域名+图片路径

**Comment by Kuingsmile** [comment]
预计于下版本添加自定义功能

**Comment by Kuingsmile** [comment]
closed in https://github.com/Kuingsmile/PicHoro/commit/569f748323567494b90a1399e53d9e689236eed2
