### ISSUE TITLE
[Bug]: 无法进入软件

### ISSUE THREAD

**Issue by sucooer** [Kuingsmile/PicHoro#49]
### PicHoro的版本

1.9.9

### 系统信息

魅族16s，安卓10

### 问题重现 | Bug reproduce

打开软件就是白屏，无法进入![S30121-13503838](https://user-images.githubusercontent.com/59865283/213845687-bcd0be54-b4d2-4bb8-bd7a-6e82c60d642d.png)

**Comment by Kuingsmile** [comment]
参考 #29  试一下，估计是有权限没有给的问题

**Comment by sucooer** [comment]
解决了，得手动给安装未知应用权限

**Comment by Kuingsmile** [comment]
> 解决了，得手动给安装未知应用权限

好的  现在安装未知应用的权限是在手动更新的时候才会主动获取，而不是第一次启动的时候，估计是这个原因。
后面我把这个的权限请求移动到第一次启动APP的时候应该就可以不用手动设置了。
