### ISSUE TITLE
[Bug]: 应用安装失败

### ISSUE THREAD

**Issue by LZS12** [Kuingsmile/PicHoro#50]
### PicHoro的版本

1.9.9

### 系统信息

华为鸿蒙系统3.0 mate305g

### 问题重现 | Bug reproduce

安装包安装时显示解析包失败。

**Comment by HurricanMaple** [comment]
我的是鸿蒙2.0，安装后打开黑屏

**Comment by Kuingsmile** [comment]
> 我的是鸿蒙2.0，安装后打开黑屏

试一下手动给下权限  参考 #49 
软件需要的权限有：

网络连接权限
存储：允许管理所有文件
相机权限
访问和写入剪贴板权限
使用摄像头权限
安装未知应用权限
