### ISSUE TITLE
[Feature]: 请求添加gitee图床

### ISSUE THREAD

**Issue by LZS12** [Kuingsmile/PicHoro#51]
### PicHoro的版本

1.9.8

### 系统信息

华为鸿蒙系统3.0 mate305g

### 功能请求

请求添加gitee图床

**Comment by Kuingsmile** [comment]
> ### PicHoro的版本
> 1.9.8
> 
> ### 系统信息
> 华为鸿蒙系统3.0 mate305g
> 
> ### 功能请求
> 请求添加gitee图床

gitee不是已经封了外链没法当图床了嘛

**Comment by LZS12** [comment]
这样嘛！我这居然还在用。


&nbsp;


Gabriela
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月15日(星期三) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kuingsmile/PicHoro] [Feature]: 请求添加gitee图床 (Issue #51)





  
PicHoro的版本
 
1.9.8
 
系统信息
 
华为鸿蒙系统3.0 mate305g
 
功能请求
 
请求添加gitee图床
  
gitee不是已经封了外链没法当图床了嘛

**Comment by Kuingsmile** [comment]
https://www.zhihu.com/question/524094354
