### ISSUE TITLE
增加对于telegraph存储的支持[Feature]: 

### ISSUE THREAD

**Issue by Calle-99** [Kuingsmile/PicHoro#60]
### PicHoro的版本

2.4.0

### 系统信息

小米13

### 功能请求

增加对于telegraph存储的支持

**Comment by Kuingsmile** [comment]
telegram？

**Comment by Calle-99** [comment]
> 电报？还是说的电报电报？

忘记带仓库链接了，是下面这个
https://github.com/secflag/picgo-plugin-telegraph-image

**Comment by Kuingsmile** [comment]
太小众 不考虑支持

**Comment by Calle-99** [comment]
> 太小众 不考虑支持

挺多人使用telegraph存储的，只需要一个cloudflare账号就可以部署图床
https://github.com/cf-pages/Telegraph-Image
