### ISSUE TITLE
[Feature]: 可否增加支持极狐lab图床

### ISSUE THREAD

**Issue by javon4016** [Kuingsmile/PicHoro#61]
### PicHoro的版本

v2.1.1

### 系统信息

华为荣耀 nova 9

### 功能请求

首先感谢作者的好软件。极狐lab作为图床挺好用的，作者能否支持下这个图床。

**Comment by Kuingsmile** [comment]
gitlab嘛 可以

**Comment by javon4016** [comment]
> gitlab嘛 可以

是的，极狐GitLab SaaS(JihuLab.com)，感谢👍👍

**Comment by Kuingsmile** [comment]
预计2个版本内添加，我正在将项目从flutter 3.3迁移到3.13版本，整体要先重构下
