### ISSUE TITLE
打开软件跳出申请安装未知软件界面

### ISSUE THREAD

**Issue by Gsirr** [Kuingsmile/PicHoro#64]
### PicHoro的版本

V2.1.2

### 系统信息

MEIZU 16T

### 问题重现 | Bug reproduce

每次一打开软件就跳出申请安装未知软件的界面，打开同意开关之后就不会再跳出该页面；或者每次跳出页面的时候，点击返回就可以正常进入软件主页。

**Comment by Kuingsmile** [comment]
> ### PicHoro的版本
> V2.1.2
> 
> ### 系统信息
> MEIZU 16T
> 
> ### 问题重现 | Bug reproduce
> 每次一打开软件就跳出申请安装未知软件的界面，打开同意开关之后就不会再跳出该页面；或者每次跳出页面的时候，点击返回就可以正常进入软件主页。
> 
> ### 相关日志 | Logs
> _No response_

这个是自动更新功能需要的权限，由于本软件没有去申请软著上架，所以会被识别为未知软件，直接打开权限就行了，代码都在仓库，不会给你安装乱七八糟的软件的

**Comment by Gsirr** [comment]
嗯嗯，好的，谢谢讲解


来自 16T

-------- 原始邮件 --------
发件人：Kuingsmile ***@***.***>
时间：2023年8月16日 06:45
收件人：Kuingsmile/PicHoro ***@***.***>
抄送：Gsirr ***@***.***>,Author ***@***.***>
主题：Re: [Kuingsmile/PicHoro] 打开软件跳出申请安装未知软件界面 (Issue #64)
