### ISSUE TITLE
[Feature]: 上传相册图片使用类似相册应用程序页面

### ISSUE THREAD

**Issue by QiqiXian** [Kuingsmile/PicHoro#65]
### PicHoro的版本

V2.0.0

### 系统信息

Xiaomi 10 S

### 功能请求

希望上传图片时的预览界面可以直接接入相册，类似qq而非现在像微信发送照片的选择页面，只能按编辑时间排序，无法像在原相册应用程序中选择不同排序方式。

或者在相册中选择图片后，可以类似发送到微信一样，有上传到Pichoro的快捷入口（不知道容不容易实现）

（已赞，非常好的项目）

**Comment by Kuingsmile** [comment]
第二个我研究下看看能实现不

**Comment by Kuingsmile** [comment]
@QiqiXian  相册分享功能已添加
