### ISSUE TITLE
[Feature]: 关于ios/mac下编译运行问题

### ISSUE THREAD

**Issue by tangyiyong** [Kuingsmile/PicHoro#70]
### PicHoro的版本

v2.2.2

### 系统信息

iphone12pm

### 功能请求

首先这是一个很棒的项目，谢谢分享。
我最近在找七牛云的flutter接口，搜到这个项目，打算在ios上运行，这个项目正好支持七牛云、阿里云等接口，就重新整理了一下插件的依赖关系，编译了一下；可以编译通过，生成ipa/app文件；但是调试运行后显示错误，简单debug后发现以下可能的两个问题：

1: mainInit() 开始的permission_handler权限检查部分，android、windows和ios、mac处理方式不一样；
2: external_path只支持android，考虑同时支持ios/mac的话，可能要用path_provider替换（这个插件支持android/ios/mac/windows/linux），并且可能要重新划分文件存储的方式；毕竟anrdoid和ios下文件目录结构差异比较大；

编译平台是flutter 3.13.5，m1 macos 13.5.2, ios 17.0.1. xcode 15.

**Comment by Kuingsmile** [comment]
由于我没有苹果电脑/手机，没法做调试，所以这个项目一开始写的时候就没有考虑对ios的适配哈

**Comment by tangyiyong** [comment]
明白，那我自己fork个分支尝试修改一下看看
