### ISSUE TITLE
[Bug]: 兰空图床的albumId设置无效

### ISSUE THREAD

**Issue by Yurzi** [Kuingsmile/PicHoro#71]
### PicHoro的版本

V2.2.2

### 系统信息

Redmi K60 Ultra

### 问题重现 | Bug reproduce

1. 设置兰空图床参数并指定相册id（兰空图床侧已经做了相应的修改）
2. 进行图片上传

这里的代码似乎存在逻辑错误
https://github.com/Kuingsmile/PicHoro/blob/6035caaeee7a3bccfb1e57516c3152e713252dc5/lib/api/lskypro_api.dart#L22-L38

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/PicHoro/commit/c39a1500b579b2ce8e148b5f0f7ba3ebacd9878d
