### ISSUE TITLE
[Feature]: 相册界面的缩略图显示改进与上传界面的备选配置快速切换

### ISSUE THREAD

**Issue by Yurzi** [Kuingsmile/PicHoro#72]
### PicHoro的版本

V2.2.2

### 系统信息

Redmi K60 Ultra

### 功能请求

**相册界面**
1. 在相册页面能根据图片的缩略图的尺寸比例显示图片
2. 或许可以将相册页面设计成瀑布流的形式（？
**上传界面**
1. 添加一个按钮用于切换当前图床下的多个不同的备选配置（或者复用右上角的设置？

**Comment by Kuingsmile** [comment]
瀑布流估计不太好修改 得测试测试

**Comment by Kuingsmile** [comment]
已经修改相册页面形式，更类似系统相册的平滑滚动
