### ISSUE TITLE
图片可以预览，视频不能播放

### ISSUE THREAD

**Issue by xieyuhua** [Kuingsmile/PicHoro#73]
### PicHoro的版本

v2.2.2

### 系统信息

三星s20

### 问题重现 | Bug reproduce

阿里云oss,图片可以预览，视频打开就是白屏没有反应

**Comment by Kuingsmile** [comment]
get 周末看看

**Comment by Kuingsmile** [comment]
传入的链接没有正确解析为uri类型导致，已在https://github.com/Kuingsmile/PicHoro/commit/e75b7b14671faa5da08f8e08e67bea03dd824fda 修复
