### ISSUE TITLE
[Bug]: 通过AList V3链接 Onedrive，一段时间后无法在相册查看已上传图片

### ISSUE THREAD

**Issue by freejishu** [Kuingsmile/PicHoro#75]
### PicHoro的版本

v2.2.3

### 系统信息

Xiaomi 13

### 问题重现 | Bug reproduce

通过Alist V3链接Onedrive for Business，上传图片后一段时间再次打开APP，发现Alist相册中图片全部呈现感叹号，如下图：
![Screenshot_2023-12-03-14-37-30-910_com example horopic](https://github.com/Kuingsmile/PicHoro/assets/11630435/1d4d0764-56a8-4d58-b77f-ecbf63fbf0d6)

尝试复制URL到浏览器直接访问，sharepoint给出提示：
The access token has expired. It's valid from '11/28/2023 3:03:23 PM' and to '11/28/2023 4:03:23 PM'.

猜测通过alist获取的onedrive真实文件访问链接是存在有效期的。所以此种链接不适合长期分享，只短期分享可用。

不知是否有意向优化，如有，能想到的优化建议：
1、对于alist获取到的onedrive链接，每次访问时调用alist接口刷新（没接触过alist的api，只是按逻辑推测）
2、增加刷新按钮（开销较高）
3、相册缓存时缓存alist的重新解析的链接

该问题可能不符合大多数pichoro的场景，所以也只是告知问题，是否修复请大佬们定夺Orz

**Comment by Kuingsmile** [comment]
> ### PicHoro的版本
> v2.2.3
> 
> ### 系统信息
> Xiaomi 13
> 
> ### 问题重现 | Bug reproduce
> 通过Alist V3链接Onedrive for Business，上传图片后一段时间再次打开APP，发现Alist相册中图片全部呈现感叹号，如下图： ![Screenshot_2023-12-03-14-37-30-910_com example horopic](https://private-user-images.githubusercontent.com/11630435/287501387-1d4d0764-56a8-4d58-b77f-ecbf63fbf0d6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTE3MTEsIm5iZiI6MTcwMTU5MTQxMSwicGF0aCI6Ii8xMTYzMDQzNS8yODc1MDEzODctMWQ0ZDA3NjQtNTZhOC00ZDU4LWI3N2YtZWNiZjYzZmJmMGQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDA4MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZmYwYTMxZTIwZjM5NGVjMTMyMmI1YzNhZGRiMGQ2YzhlMjc0OTRmZTdiZTVjNDBkYWM2MzJlMzZhYWJkMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nGT92myFdJN54QabtlNXuc8w8ncLX3fhT8X7h383G-0)
> 
> 尝试复制URL到浏览器直接访问，sharepoint给出提示： The access token has expired. It's valid from '11/28/2023 3:03:23 PM' and to '11/28/2023 4:03:23 PM'.
> 
> 猜测通过alist获取的onedrive真实文件访问链接是存在有效期的。所以此种链接不适合长期分享，只短期分享可用。
> 
> 不知是否有意向优化，如有，能想到的优化建议： 1、对于alist获取到的onedrive链接，每次访问时调用alist接口刷新（没接触过alist的api，只是按逻辑推测） 2、增加刷新按钮（开销较高） 3、相册缓存时缓存alist的重新解析的链接
> 
> 该问题可能不符合大多数pichoro的场景，所以也只是告知问题，是否修复请大佬们定夺Orz
> 
> ### 相关日志 | Logs
> _No response_

应该是sign的过期时间导致的 查考alist issue https://github.com/alist-org/alist/discussions/1688

这里直链有效期改成0 就是永不过期试下
![image](https://github.com/Kuingsmile/PicHoro/assets/96409857/292e87f2-7b2c-49b0-9687-5b4dc0badc99)

**Comment by freejishu** [comment]
感谢回复~~~~

--- 

此处设置一直为0，和这个应该关系不大
![image](https://github.com/Kuingsmile/PicHoro/assets/11630435/d6021d2c-a223-452a-9280-b2622da3606d)

---

刚才详细测试了下，发现似乎app中相册缓存的url是此处的url

![image](https://github.com/Kuingsmile/PicHoro/assets/11630435/88ce8abd-19ec-4a01-ad70-60e796c1866b)

后台Onedrive储存设置如果使用302，则会返回此种onedrive的直链；看起来这种链接会过期；

如果更改为本地代理，返回 域名/d/文件 的链接；看起来这种链接是可以保持长效的？（是不是这种会使得alist每次访问时都会进行解析）

所以：如果app缓存的链接为调用raw_url的链接，确实就会导致此种问题；那只能依靠alist的后台设置进行处理了，那能想到的就是在alist再挂一个一模一样的存储，新的设定为“本机代理”了；估计ondrive侧的链接过期问题不好处理，不知道有没有策略可以控制。

按照上述逻辑，好像这不是bug，是我自己乌龙了 qaq
