### ISSUE TITLE
[Bug]: S3兼容平台桶名称无法识别大写

### ISSUE THREAD

**Issue by Usertao5823** [Kuingsmile/PicHoro#79]
### PicHoro的版本

V2.2.4

### 系统信息

IQOO11

### 问题重现 | Bug reproduce

桶的名称为taoImg，在检查当前配置时无法通过，需改成taoimg，但是在图床管理-S3存储桶管理列表中获取到的桶名是大写的，以及无法获取区域和云端文件

![7C475CE8DB54607C72AA820BACD53A3A](https://github.com/Kuingsmile/PicHoro/assets/64523185/a0e2223f-02c0-4318-b277-2d6db9fe0630)
![F31FAA9FDEAEECE15E136726E11FBFFD](https://github.com/Kuingsmile/PicHoro/assets/64523185/0dcecc40-9373-44a5-9014-4e1675081838)

### 相关日志 | Logs

39
记录时间: 26 February 2024 09:51:24 AM
类名: AwsManageAPI
方法名: getBucketList
日志级别: LogLevel.ERROR
日志内容: 参数:

错误信息:
MinioError: Invalid bucket name: taoImg

是否DIO错误:
false

DIO报错信息:

31
记录时间: 26 February 2024 09:44:53 AM
类名: AwsConfigPage
方法名: checkAwsConfig
日志级别: LogLevel.ERROR
日志内容: 参数:

错误信息:
MinioError: Invalid bucket name: taoImg

是否DIO错误:
false

DIO报错信息:

**Comment by Kuingsmile** [comment]
你的截图里泄露了你的密钥配置，我帮你把图片删掉了哈
具体问题我先测试下

**Comment by Kuingsmile** [comment]
s3平台使用了的包内置了对存储桶名的检测，同时大部分的平台，都不允许设置带有大写字母的bucket名，所以我没法测试，但已经修改了依赖包先跳过了对大写字母的检测
