### ISSUE TITLE
[Bug]: 每次启动应用自动请求“安装未知应用”权限

### ISSUE THREAD

**Issue by Vekixx** [Kuingsmile/PicHoro#80]
### PicHoro的版本

v2.2.4

### 系统信息

Xiaomi 13U HyperOS

### 问题重现 | Bug reproduce

每次启动应用，自动跳转“安装未知应用”权限管理页面，要求给予pichoro“安装未知应用”的权限，给予其“安装未知应用”权限后，不再打开管理权限的页面。
其中，“安装未知应用”为高度敏感权限，为何pichoro需要此权限呢？

### 相关日志 | Logs

打开就跳转此页面：https://c.vekixx.com/i/2024/03/09/65ec66bed438d.webp

**Comment by Kuingsmile** [comment]
自动更新功能的需要，要下载安装包并自动安装
我没去申请软著和上架，所以会被识别到未知软件
不放心的话可以查看对应自动更新部分代码

https://github.com/Kuingsmile/PicHoro/blob/main/lib%2Fconfigure_page%2Fconfigure_page.dart
