### ISSUE TITLE
[Bug]: github图床显示上传失败

### ISSUE THREAD

**Issue by 948812757** [Kuingsmile/PicHoro#82]
### PicHoro的版本

V2.2.4

### 系统信息

ViVo IQOO Z6X

### 问题重现 | Bug reproduce

打开上传自动复制链接后 再将默认链接格式选择为BBcode格式的话 使用github图床会显示图片上传失败，然而实际是已经上传成功了，只是在客户端这边显示的是上传失败

### 相关日志 | Logs

23
记录时间: 07 April 2024 02:31:07 PM
类名: UploadTask
方法名: start
日志级别: LogLevel.ERROR
日志内容: 参数:

path: /data/user/0/com.example.horopic/cache/チョコメルト_116056256.jpeg
fileName: チョコメルト_116056256.png

错误信息:
Exception: 上传失败

是否DIO错误:
false

DIO报错信息:

22
记录时间: 07 April 2024 02:31:07 PM
类名: GithubImageUploadUtils
方法名: uploadApi
日志级别: LogLevel.ERROR
日志内容: 参数:

path: /data/user/0/com.example.horopic/cache/チョコメルト_116056256.jpeg
name: チョコメルト_116056256.png

错误信息:
Null check operator used on a null value

是否DIO错误:
false

DIO报错信息:

**Comment by Kuingsmile** [comment]
好的 我试试复现

**Comment by Kuingsmile** [comment]
已修复，下个版本发布
