### ISSUE TITLE
[Bug]: 上传路径不支持占位符

### ISSUE THREAD

**Issue by onlyistranger** [Kuingsmile/PicHoro#83]
### PicHoro的版本

v2.2.4

### 系统信息

mate30

### 问题重现 | Bug reproduce

测试了{Y}{m}，直接创建了字面字符文件夹

**Comment by Kuingsmile** [comment]
上传到哪个图床的 我测试到github没问题 设置为`{Y}{filename}` 结果如下
![21a21fb604e03b88e678ee2d2c8bb4f](https://github.com/Kuingsmile/PicHoro/assets/96409857/9d627e62-c511-4ae6-b83c-3d36d8cd1cfc)
![image](https://github.com/Kuingsmile/PicHoro/assets/96409857/d6692cc2-51d5-4dce-b439-03bd5624b1b4)

**Comment by onlyistranger** [comment]
用的是cloudflare的R2
文件名里的占位符正常，路径里不正常。路径里填写 public/{Y}/{m}/，上传后创建了{Y}和{m}两个文件夹，而不是2024和04两个文件夹

**Comment by Kuingsmile** [comment]
> 用的是cloudflare的R2 文件名里的占位符正常，路径里不正常。路径里填写 public/{Y}/{m}/，上传后创建了{Y}和{m}两个文件夹，而不是2024和04两个文件夹

路径里本身就不支持占位符，需要根据日期创建文件夹的话，直接在文件重命名里写`{Y}/{m}/{filename}`就行

**Comment by onlyistranger** [comment]
按 {Y}/{m}/{filename} 路径正常了，但创建的文件夹对应月份只有1位而不是两位，即4而不是04。

Kuingsmile ***@***.***> 于 2024年4月13日周六 17:02写道：
