### ISSUE TITLE
[Bug]: 设定oss参数配置-网址后缀时会自动添加一个“ ？”

### ISSUE THREAD

**Issue by changeen** [Kuingsmile/PicHoro#85]
### PicHoro的版本

最新

### 系统信息

x90pro+

### 问题重现 | Bug reproduce

[Bug]: 在添加网址后缀时会自动添加一个“ ？”

**Comment by Kuingsmile** [comment]
因为网址后缀这里本身就是设置url参数的呀 就是url的?后面的部分
