### ISSUE TITLE
[Feature]: 上传列表点击单个文件复制链接容易实现吗？

### ISSUE THREAD

**Issue by changeen** [Kuingsmile/PicHoro#86]
### PicHoro的版本

最新

### 系统信息

x90pro+

### 功能请求

感谢作者。解决我目前的试用场景：手机相册上传博客。

**Comment by Kuingsmile** [comment]
上传列表里都是临时信息 如果需要复制链接是在相册里的 另外是支持上传完之后自动复制到剪贴板的
