### ISSUE TITLE
实际上传格式与文档提示格式不同

### ISSUE THREAD

**Issue by TenTh0usand** [Kuingsmile/PicHoro#87]
### PicHoro的版本

V2.3.0

### 系统信息

Redmi Note 13 pro +

### 问题重现 | Bug reproduce

s3储存(实际设置的是cloudflare r2)，按照这里的提示设置`{m}`输出应该为`01` `02` `05`，实际输出为`5`。  

以下为碎碎念
跟我电脑上传的时间格式不同（为05），导致没有合并为一个路径，而且没有解决办法，只能给手机专门加了个mobile路径
而且此软件的时间格式跟picgo不同啊，我电脑端设置的是`{year}/{month}/{md5}.{extName}`，不过也无所谓了

![Screenshot_2024-05-17-21-54-22-931_com example horopic](https://github.com/Kuingsmile/PicHoro/assets/148879701/5c2ff492-007f-411a-bde1-7c8795b8a808)

**Comment by Kuingsmile** [comment]
{m}的问题这两天会改下

**Comment by Kuingsmile** [comment]
{m}的问题已修改 同时新增了{h} {i} {s} {ms}等的支持
