### ISSUE TITLE
[Bug]: GitHub 图传无法上传

### ISSUE THREAD

**Issue by beixinti** [Kuingsmile/PicHoro#89]
### PicHoro的版本

2.3.0

### 系统信息

魅族 20

### 问题重现 | Bug reproduce

如题
![S40626-19572409_com example horopic(1)](https://github.com/Kuingsmile/PicHoro/assets/95170151/84acec1f-8c44-45e0-9163-2303d51cd196)

### 相关日志 | Logs

3
记录时间: 26 June 2024 07:59:42 PM
类名: UploadTask
方法名: start
日志级别: LogLevel.ERROR
日志内容: 参数:

path: /storage/emulated/0/Pictures/Image_1719383553482.gif
fileName: 1719403180426.gif

错误信息:
Exception: 上传失败

是否DIO错误:
false

DIO报错信息:

2
记录时间: 26 June 2024 07:59:42 PM
类名: GithubImageUploadUtils
方法名: uploadApi
日志级别: LogLevel.ERROR
日志内容: 参数:

path: /storage/emulated/0/Pictures/Image_1719383553482.gif
name: 1719403180426.gif

错误信息:
DioException [bad response]: The request returned an invalid status code of 404.

是否DIO错误:
true

DIO报错信息:
The request returned an invalid status code of 404.
{message: Not Found, documentation_url: https://docs.github.com/rest, status: 404}

1
记录时间: 26 June 2024 07:59:33 PM
类名: HomePage
方法名: _initIntent
日志级别: LogLevel.ERROR
日志内容: 参数:

intent: Intent(fromPackageName: null, fromSignatures: null, action: android.intent.action.MAIN, data: null, categories: [android.intent.category.LAUNCHER], extra: null)

错误信息:
Null check operator used on a null value

是否DIO错误:
false

DIO报错信息:

**Comment by Kuingsmile** [comment]
![image](https://github.com/Kuingsmile/PicHoro/assets/96409857/e432ff17-d24c-4b6b-98b9-a20adf2aed47)
Github用户名写错了 仓库名里不要加用户名

**Comment by beixinti** [comment]
感谢告知，用户名写错了 确实是我粗心大意了🤣
