### ISSUE TITLE
[Bug]: 又拍登录失败，已经确认密码没问题，但是显示登录失败

### ISSUE THREAD

**Issue by chendada00** [Kuingsmile/PicHoro#92]
### PicHoro的版本

最新版

### 系统信息

14U

### 问题重现 | Bug reproduce

![1721635908462](https://github.com/user-attachments/assets/1ee25288-2fed-4d27-9745-5f1a07820a5b)

**Comment by Kuingsmile** [comment]
不能复现 我登录正常

**Comment by chendada00** [comment]
是用又拍云的账号密码登录吧

**Comment by Kuingsmile** [comment]
是的

**Comment by Kuingsmile** [comment]
看下日志是否有相关报错信息

**Comment by chendada00** [comment]
![Screenshot_2024-07-23-09-22-17-836_com example horopic](https://github.com/user-attachments/assets/2658c130-9efe-45d4-8252-74e22dadc163)

**Comment by Kuingsmile** [comment]
![image](https://github.com/user-attachments/assets/25656b23-9d48-4270-8f19-2e9b7a7b68f6)
这条往下滑一下 应该有具体报错信息，我试了下填错密码的时候报错码是400

**Comment by chendada00** [comment]
![Screenshot_2024-07-25-15-57-16-722_com example horopic](https://github.com/user-attachments/assets/26d6c7c2-6b94-4c3f-98c4-010245fc39d7)

**Comment by Kuingsmile** [comment]
看着是访问api.upyun.com出错了？
