### ISSUE TITLE
[Feature]: 复制链接格式的自定义格式可以提供文件重名的自定义变量吗？

### ISSUE THREAD

**Issue by clover1420** [Kuingsmile/PicHoro#97]
### PicHoro的版本

v2.4.0

### 系统信息

xiaomi14

### 功能请求

![image](https://github.com/user-attachments/assets/1a754d97-5777-465b-a9a9-5e41c0e98b12)

**Comment by Kuingsmile** [comment]
这个不考虑哈 复制链接时的文件名、链接等信息已固定
